Feature/2 todo 전체 조회
grow-up-study/todoary pull request #4
Opened 2023-09-29 04:15 UTC by daheeParkk

# 🔥 연관 이슈

- close #3

# 🚀 작업 내용
- controller, service, repository를 만들고 todo 전체 조회하는 기능을 만들었습니다!
  - todo 리스트와 http status code를 함께 반환합니다.

- .gitignore에서 README.md를 제외하였습니다.
---
- 로컬 테스트
postman에서 요청하였을 때 빈 배열과 200 ok가 뜨는 것을 확인하였습니다.

# 💬 리뷰 중점사항

2023-09-29 13:54 UTC, Choi-JJunho requested changes
몇가지 내용 확인 부탁드려요~

2023-09-29 13:54 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/controller/TodoController.java
> +@Controller
`@RestController` 를 사용해보는건 어떨까요

2023-09-29 13:54 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/controller/TodoController.java
> +        return new ResponseEntity<>(todoService.getTodos(), HttpStatus.OK);
정적 메소드를 사용해서 표현할 수 있겠네요
```suggestion
        return ResponseEntity.ok(todoService.getTodos());
```

2023-09-29 13:54 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/service/TodoService.java
> +public class TodoService {
`@Transactional(readOnly=true)` 어노테이션을 추가해주는건 어떨까요?

2023-09-29 13:54 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/repository/TodoRepository.java
> +}
entityManager를 직접 이용하는 방식이군요..!
간단한 CURD작업에 대한 생산성을 높이기 위해 JPARepository를 이용해보는건 어떨까요?

2023-09-29 13:54 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/service/TodoService.java
> +    }
위에서 이야기한 JPARepository를 이용한 형태로 변경하면 다음과 같이 바뀌겠군요

```suggestion
    public List<Todo> findAll() {
        return todoRepository.findAll();
    }
```

2023-09-30 08:06 UTC, daheeParkk commented on src/main/java/com/growup/todoary/controller/TodoController.java
> +@Controller
넵! 객체를 반환하니까 `@RestController`를 사용하는게 맞는 것 같습니다

2023-09-30 08:06 UTC, daheeParkk commented on src/main/java/com/growup/todoary/controller/TodoController.java
> +        return new ResponseEntity<>(todoService.getTodos(), HttpStatus.OK);
정적 메소드를 사용하도록 바꾸겠습니다!

2023-09-30 08:06 UTC, daheeParkk commented on src/main/java/com/growup/todoary/service/TodoService.java
> +public class TodoService {
추가하겠습니다!

2023-09-30 08:06 UTC, daheeParkk commented on src/main/java/com/growup/todoary/repository/TodoRepository.java
> +}
넵! JPARepository를 잘 몰랐는데 간편하게 CRUD를 조작할 수 있어서 좋은 것 같습니다.

2023-09-30 08:07 UTC, daheeParkk commented on src/main/java/com/growup/todoary/service/TodoService.java
> +    }
넵 JpaRepository를 사용하는 방법으로 바꾸겠습니다

2023-09-30 08:38 UTC, daheeParkk commented
아래 내용들을 수정하였습니다.

- `@Controller` → `@RestController`로 변경
- ResponseEntity.ok() 정적 메서드 사용
- `@Transactional(readOnly = true)` 추가
- JpaRepository 인터페이스를 상속받도록 변경

2023-09-30 08:54 UTC, Choi-JJunho approved these changes
확인했습니다~ 👍

2023-09-30 08:55 UTC, merged