Feature/5 todo 단건 조회
grow-up-study/todoary pull request #6
Opened 2023-09-30 15:14 UTC by daheeParkk

# 🔥 연관 이슈

- close #5

# 🚀 작업 내용
id를 받으면 id에 해당하는 todo를 반환하는 api입니다.
id에 해당하는 todo가 없을 경우 NotExistentTodoException이 발생하도록 하였습니다.
- exception과 관련하여 만든 클래스
  - ExceptionMessage
  - GlobalExceptionHandler
  - NotExistentTodoException
- 로컬 테스트
  - todo/1로 요청을 보냈을 때 "존재하지 않는 todo입니다." 메시지와 400 코드가 나오는 것을 확인

# 💬 리뷰 중점사항

2023-10-01 06:49 UTC, Choi-JJunho requested changes
몇가지 내용 확인 부탁드립니다

2023-10-01 06:49 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/exception/NotExistentTodoException.java
> +public class NotExistentTodoException extends RuntimeException{
네이밍이 약간 읽기 어렵다는 느낌을 받았어요
존재하지 않는 Todo... IllegalStateException과 같은 느낌이 드는데 자원의 관점에서 생각하려다보니 위와같은 네이밍이 도출된 것 같아요
자원에 접근하려는 클라이언트(개발자)의 관점에서 네이밍을 생각해보는건 어떤가요?
예를들면 다음과 같은 네이밍이 떠오르네요
`TodoNotFoundException`

+) 사소한 부분이지만 공백이 하나 없네요
```suggestion
public class NotExistentTodoException extends RuntimeException {
```

2023-10-01 06:49 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/service/TodoService.java
> +    }
이전 내용과 함께 이야기합니당
get... 과 같은 네이밍은 Getter의 성격을 많이 띈다고 생각해요!
사용하는쪽에서 `todoService.getTodos()`, `todoService.getTodo(id)` 와 같이 표현된다고 생각하고 적절한 네이밍을 생각해보는건 어떨까요?
저는 `todoService.findAll()`, `todoService.findById()` 와 같은 네이밍이 생각나네요

2023-10-01 06:49 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/exception/ExceptionMessage.java
> +    NOT_EXISTENT_TODO("존재하지 않는 todo입니다.");
아래 Exception 네이밍과 같은 내용입니다
`NOT_EXISTENT_TODO` -> `TODO_NOT_FOUND` 와 같은 네이밍은 어떤가요

2023-10-01 08:09 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/controller/TodoController.java
>      }
Todo 도메인 자체를 View로 넘기는것이 괜찮을까요?
DTO를 사용하는건 어떤가요?

dto는 어느 패키지에 있어야할까요?

2023-10-01 13:01 UTC, daheeParkk commented on src/main/java/com/growup/todoary/controller/TodoController.java
>      }
코드 변경이 일어났을 때를 대비해 DTO를 사용해 넘겨야할 것 같습니다!
dto 패키지 안에 response 패키지와 request 패키지를 구분하여, 응답하는 DTO는 response 패키지에 넣으면 좋을 것 같습니다

2023-10-01 13:02 UTC, daheeParkk commented on src/main/java/com/growup/todoary/exception/ExceptionMessage.java
> +    NOT_EXISTENT_TODO("존재하지 않는 todo입니다.");
`TODO_NOT_FOUND`가 더 읽기 편할 것 같습니다!

2023-10-01 13:02 UTC, daheeParkk commented on src/main/java/com/growup/todoary/service/TodoService.java
> +    }
`todoService.findAll()`, `todoService.findById()`가 명확해서 사용하기 더 좋아보입니다! 이렇게 수정하겠습니다

2023-10-01 13:02 UTC, daheeParkk commented on src/main/java/com/growup/todoary/exception/NotExistentTodoException.java
> +public class NotExistentTodoException extends RuntimeException{
`TodoNotFoundException`이 훨씬 나아 보이네요..!

2023-10-01 14:38 UTC, daheeParkk commented
- 수정 사항
  - NotExistentTodoException -> TodoNotFoundException 으로 변경
  - NOT_EXISTENT_TODO -> TODO_NOT_FOUND 으로 변경
  - getTodos() -> findAll() 로 변경
  - getTodo() -> findById() 로 변경
  - Todo -> TodoResponse 반환
  - RuntimeException과 '{' 사이 공백 추가

2023-10-01 15:13 UTC, Choi-JJunho requested changes
반영 잘해주셨네요 👏
몇가지 내용만 추가로 확인 부탁드려요~

2023-10-01 15:13 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<String> notExistentTodo(TodoNotFoundException e) {
함수명을 다음과 같이 변경하는건 어떨까요?

```suggestion
    public ResponseEntity<String> todoNotFoundHandler(TodoNotFoundException e) {
```

2023-10-01 15:13 UTC, Choi-JJunho commented on src/main/java/com/growup/todoary/service/TodoService.java
> +    public List<Todo> findAll() {
해당 메소드는 아직 dto가 아닌 도메인을 반환하고있네요?

2023-10-02 04:21 UTC, daheeParkk commented on src/main/java/com/growup/todoary/service/TodoService.java
> +    public List<Todo> findAll() {
해당 pr과 다른 api라서 새로운 pr을 날려야 하나 고민했습니다..!
findAll api도 dto를 반환하도록 수정하겠습니다!

2023-10-02 04:21 UTC, daheeParkk commented on src/main/java/com/growup/todoary/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<String> notExistentTodo(TodoNotFoundException e) {
수정하겠습니다!

2023-10-02 05:10 UTC, daheeParkk commented
- 수정 사항
  - notExistentTodo에서 todoNotFoundHandler로 변경
  - findAll() 메서드 반환 타입 DTO로 변경

2023-10-02 05:22 UTC, Choi-JJunho approved these changes
반영 잘해주셨네요 👍

2023-10-02 05:23 UTC, merged